-- // SERVER SETTINGS written by KingCreoo on 5-27-2025
-- // Holds server settings we wouldn't want exploiters to see :)

-- // Define module
local SERVER_SETTINGS = {}

-- // Settings

SERVER_SETTINGS.LEVEL_INFO = {
    ["TactileWorld"] = {
        ["Level1"] = {
            ["Type"] = "Defense",
            ["TotalTime"] = 90,
            ["StartEntities"] = {

            },
            ["EntitySequence"] = {

            }
        }
    }
}

-- // Return module
return SERVER_SETTINGS