-- // Settings, created by KingCreoo on 5-27-2025
-- // Lists basic game settings

-- // Define module
local SETTINGS = {}

SETTINGS.DEFAULT_DATA = {
    ["leaderstats"] = {
        ["Gold"] = 100,
        ["Gems"] = 10
    },
    ["Worlds"] = {
        ["Tactile"] = {
            ["Level1"] = 0,
            ["Level2"] = 0,
            ["Level3"] = 0,
            ["Level4"] = 0,
            ["Level5"] = 0
        }
    },
    ["Operators"] = {
        ["Gatling"] = 0
    }
}

-- // Return module
return SETTINGS